# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Shop.destroy_all
Shop.create(name:"BRAKE MASTER CYLINDER", description:"Master brake cylinder is the central element of the braking system, which converts the force applied to the brake pedal into the hydraulic pressure throughout the system.",image:"https://cdn.pkwteile.de/thumb/assets/ersatz_categories/200x250/104.jpg",stock:20 , price:349)
Shop.create(name:"BRAKE PADS", description:"Drum brake is one of the types of braking system, which consists of a rotating drum and braking is achieved by pressing the brake shoes to the drum. Brake pads consist of metallic components that are moon-shaped, to surface of which the shoes, made on the basis of the asbestos, are attached. On one of the pads there is placed a parking brake lever.",image:"https://cdn.pkwteile.de/thumb/assets/ersatz_categories/200x250/19.jpg",stock:60 , price:150)
Shop.create(name:"HELLA Sensor, oil temperature", description:"Oil temperature sensor is a very important smart part of modern cars. It serves to show the exact oil level in the car. As a rule it is placed at the rear part of the oil pan or oil crankcase. Since oil temperature of the operating engine usually differs from the coolant temperature and depends on many factors, you need a temperature sensor to measure it.",image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTb8ADU7Fp_DrTAsPoXgdevqatk7Olhf6xcIy2sBP9UXv1IKbpu",stock:130 , price:60)
Shop.create(name:"FUEL TANK", description:"Fuel tank is a container for keeping fuel in cars with internal-combustion engine. As automaker permanently needs gas, petrol or diesel fuel there is necessity in a built-in tank. Fuel tank is made from plastic, steel or aluminium. Many automakers use plastic as it is possible to make plastic tank of different forms. As fuel tank must correspond to the car design, plastic has a great advantage over other materials. Moreover, plastic doesn’t rust.",image:"https://cdn.autoteiledirekt.de/thumb/assets/direkt/ersatz_categories/200x250/148.jpg",stock:75 , price:890)
Shop.create(name:"RADIATOR FAN (AIR CONDITIONER FAN)", description:"Being an environmental component, engine coolant system fan is installed to speed the passage of air through the radiator core system. This provides a better heat removal from the engine coolant to the environment. System operation is essential when idling or driving at a slow speed. In these cases, the rate of air flow is not sufficient to cool the motor vehicle in full measure..",image:"https://cdn.pkwteile.de/thumb/assets/ersatz_categories/200x200/136.jpg",stock:57 , price:226)
Shop.create(name:"FREEWHEEL CLUTCH ALTERNATOR ", description:"Alternator clutch pulley is designed for adjusting for rotating torque variations, transmitted from the crankshaft to the alternator shaft. Its sleeves become uncoupled in the moments when the drive shaft slows down, allowing the driven shaft to rotate independently. As the crankshaft speeds up, engagement occurs and the clutch pulley transmits the rotating torque to the alternator shaft. This allows to avoid jerks and belt slipping, thus significantly prolonging its lifetime.",image:"https://cdn.pkwteile.de/thumb/assets/ersatz_categories/200x200/299.jpg",stock:120 , price:99)
Shop.create(name:"WINDOW SWITCH", description:"Window winder button activates a mechanism which automatically opens and closes a side window. The button unit may be mounted on the driver’s door only, or near each passenger seat as well.",image:"https://cdn.pkwteile.de/thumb/assets/ersatz_categories/200x200/325.jpg",stock:76 , price:48)
Shop.create(name:"REVERSE LIGHT SWITCH", description:"Reverse light switch is designated for activation and deactivation of corresponding lighting elements of the car.",image:"https://cdn.pkwteile.de/thumb/assets/ersatz_categories/200x200/327.jpg",stock:80 , price:34)
Shop.create(name:"PARKING SENSORS ", description:"Automatic parking system is one of the types of the active parking systems. It serves to park vehicle in an automatic or automated mode. Such systems help with parallel parking, which is the most common for today or perpendicular parking. Due to the concordance of the steering wheel angle and speed of movement the automatic parking occurs",image:"https://cdn.pkwteile.de/thumb/assets/ersatz_categories/200x200/113.jpg",stock:92 , price:55)
Shop.create(name:"WINDOW REGULATOR", description:"Window lifter is a mechanism for raising and lowering the side body and cab windows. Window lifter is a non-breaking mechanism for moving windows. Window lifters are necessary to raise and lower the windows in the car. Due to a large variety of car doors, window lifters have a great many specific names.",image:"https://cdn.pkwteile.de/thumb/assets/ersatz_categories/200x200/142.jpg",stock:120 , price:149)
Shop.create(name:"ENGINE THERMOSTAT", description:"Thermostat is a device that is used in liquid cooling systems in all existing automotive engines. Thermostat is located between the radiator and the car engine. It serves to maintain the necessary stable operating temperature of the engine. ",image:"https://cdn.pkwteile.de/thumb/assets/ersatz_categories/200x200/37.jpg",stock:90 , price:180)
Shop.create(name:"WATER PUMP", description:"An auxiliary water pump is designed to improve cooling system efficiency. It contributes to creation of comfortable microclimate in a car passenger compartment when an engine runs at low rpm, for example, in traffic jams",image:"https://cdn.pkwteile.de/thumb/assets/ersatz_categories/200x200/313.jpg",stock:120 , price:94)

